### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by justusschock** [MIC-DKFZ/batchgenerators#11]
Hi,
I've got a quick question:

Would it be possible to register `batchgenerators` at [PyPi](https://pypi.org/)? This would be really helpfull to develop packages depending on it, since this would not make a separate installation step necessary (as it is now).

Thanks!
Justus

**Comment by FabianIsensee** [comment]
Hi Justus,
we have not yet completed an actual release. The code of batchgenerators is still 'beta'. As you may have noticed we are currently working on implementing tests (all_augmentatione...something branch (which happens to be my personal one)) and once that is done we will do a release that will of course also be registered.
Until then you can add
`-e git+https://github.com/MIC-DKFZ/batchgenerators#egg=batchgenerators
`
Best,
Fabian

**Comment by justusschock** [comment]
Hi Fabian,

Sorry for digging up this old issue again.
Are there any updates regarding the new release or timeschedules? Unfortunately we can't register our project to PyPi, until batchgenerators is registered there and we don't want to tag a fixed commit there too :)

Best,
Justus

**Comment by FabianIsensee** [comment]
Hi Justus,
I see your problem and recognize we should speed up things on our end. To be honest, I have never registered a project with PyPi. How often would be be able to do updates? If we can update as often as we want then I can get batchgenerators to PyPi quite soon, otherwise I would like to finish writing tests first.
Best,
Fabian

**Comment by justusschock** [comment]
Hi Fabian, 
basically you could update your project as often as you want to.
The only limitation is, that each filename has to be unique (which is fullfilled if you append a datetime-tag at the end of your filename). 
To speed things up, I would be happy to write a few tests by myself, if any help is needed.
If so, please point me towards transforms, which need to be tested and I will try to come up with a test for them.

Best,
Justus

**Comment by FabianIsensee** [comment]
Hi Justus,
we created a bunch of tests on friday. We are not done by far but I think we should go ahead with the first release. I will get this done today.
Best,
Fabian

**Comment by justusschock** [comment]
Hi Fabian,

Thank you very much for the effort. If I am able to help, please point me to some tasks.

Best,
Justus

**Comment by FabianIsensee** [comment]
Hi Justus,

`pip install batchgenerators` should now work =) Sorry for letting you wait so long.

If you really want to help feel free to write tests as you see fit. Ideally for Transforms that you use yourself and where you know what they are supposed to. But you don't have to.

Best,
Fabian
