### ISSUE TITLE
Example.ipynb is not working!

### ISSUE THREAD

**Issue by paul-bd** [MIC-DKFZ/batchgenerators#13]
Hi, 

I have an issue with the .next attribute :

first the dataloader class is not working for me in the Example.ipynb : 

as  when doing : 
`
batchgen = DataLoader(data.camera(), 4, None, False)
batch = batchgen.next()
`
returns this error: 
`AttributeError: 'DataLoader' object has no attribute 'next'`

it can be fixed by renaming generate_train_batch in the DataLoader by next, but not sure this is the good way to do it. Indeed later, 
`multithreaded_generator = MultiThreadedAugmenter(batchgen, all_transforms, 4, 2, seeds=None)`

also as no attribute .next and when doing multithreaded_generator.generator.next() which works, the transformation didn't apply...

I don't know where the error come from,

Best regards

Paul

**Comment by Sendemast** [comment]
Hi paul-bd,

I had a similar error once, are you using python 2 or python 3?

In python 3 you have to use
`batchgen = DataLoader(data.camera(), 4, None, False) batch = next(batchgen)` instead.

**Comment by paul-bd** [comment]
Indeed thanks it's working !!

**Comment by FabianIsensee** [comment]
Thanks for pointing this out! I sent an email to respond to your issue but somehow it must have gotten lost. Thanks @Sendemast for replying.
I fixed the next() issue now. The example should work again, sorry for the inconvenience!
