### ISSUE TITLE
The pin_memory option in the MultiThreadedAugmenter might have a memory leak

### ISSUE THREAD

**Issue by Sendemast** [MIC-DKFZ/batchgenerators#14]
Hi,

It can be the case that the pin_memory option in the MultiThreadedAugmenter has a memory leak, causing the RAM to overflow. This could happen because the processes started with this command:

https://github.com/MIC-DKFZ/batchgenerators/blob/7b929305b3a68076987753a1e047d2c9e9dbef3e/batchgenerators/dataloading/multi_threaded_augmenter.py#L150-L154

are not properly stopped again.

In the dataloader from pycharm the following description is given prior to shutting down the workers 
(https://pytorch.org/docs/stable/_modules/torch/utils/data/dataloader.html):

>    Exit `pin_memory_thread` first because exiting workers may leave 
> corrupted data in `worker_result_queue` which `pin_memory_thread` reads from.

Maybe the problem can be solved if the workers are closed explicitly. I can try to fix it in the next couple of days.

**Comment by FabianIsensee** [comment]
Hi,
I agree that there can be a memory leak if you repeatedly delete and re instantiate the multithreaded augmenter. The pin_memory feature is experimental and I added it only last week. I will try to get this fixed as soon as possible. Until then, don't reinstantiate it or use pin_memory=False.

Following the way pytorch does this is very complicated (and a lot of work to integrate into our code) and I think we can try to get it running easier somehow. If you have ideas, please let me know =)

Thanks for pointing this out!
Best,
Fabian

**Comment by FabianIsensee** [comment]
All workers and the pin memory thread now use an abort_event (multiprocessing.Event) and will exit if it was set. This event can be set from various places, such as crashing workers (which would previously have resulted in the main process waiting for new data indefinitely), crashing other things or calling the destructor of MultiThreadedAugmenter. Please test and see if you still experience memory leaks. If you do, please provide a minimalistic example and I will figure out a way to solve this.
Best,
Fabian

**Comment by Sendemast** [comment]
Works perfectly now! Thanks for the quick fix!

**Comment by FabianIsensee** [comment]
No worries, it's always good to get user feedback =) Thanks a lot again for pointing out the issue
