### ISSUE TITLE
Python random seed

### ISSUE THREAD

**Issue by mibaumgartner** [MIC-DKFZ/batchgenerators#17]
Hi, great work with Batchgenerators!
The MultiThreadedAugmenter leads to some non-deterministic behaviour even when it is seeded. After some investigation, I found that only the numpy.random seed is set by the producer. Additionally setting the random seed for the random package included in python fixed my issues. Maybe you could add that seed to the producer because in your brightness augmentation you are using `random.uniform`, too.

https://github.com/MIC-DKFZ/batchgenerators/blob/af6dbab45ec9bb44c76c73e5460a540dff4c96de/batchgenerators/dataloading/multi_threaded_augmenter.py#L33-L37

https://github.com/MIC-DKFZ/batchgenerators/blob/e86abab714fb7d40c4fb2d2168755cb0e687889d/batchgenerators/augmentations/color_augmentations.py#L65-L71

**Comment by FabianIsensee** [comment]
Hi,
thanks for pointing this out. We should stick to numpy for all random numbers. However used the builtin python rng probably did not do it on purpose. I will fix this now by using np.random.uniform.
Best,
Fabian

**Comment by mibaumgartner** [comment]
Thank you for your quick response. That works too :+1:
