### ISSUE TITLE
3D image and label augmentation tutorial

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/batchgenerators#18]
Thanks for the great work.
Would it be possible for you to provide a tutorial for 3D medical image and label augmentation? 
Eg: BraTS dataset.

Looking forward to your reply.

Best regards,
Edward

**Comment by FabianIsensee** [comment]
Hi Edward,
thank you for the suggestion. That is a good idea and I will implement it, but you will have to be a little bit patient. MICCAI deadline is on April 2nd :-) After that I can do it.
Best,
Fabian

**Comment by EdwardMa12593** [comment]
Hi @FabianIsensee, thanks for your reply. I'm looking forward to your 3D medical image augmentation tutorial.

**Comment by FabianIsensee** [comment]
Hi @JunMa11 , have a look at the examples folder. I added a complete BraTS2017 example there
