### ISSUE TITLE
Sorry I did not find the folder 'dldabg'

### ISSUE THREAD

**Issue by wyzjack** [MIC-DKFZ/batchgenerators#2]
there is a command 'cd dldabg' but I did not find the folder

**Comment by FabianIsensee** [comment]
I suppose that is in the documentation? Sorry for that, this repo has a different name on our internal server. I changed it in the documentations. You need to cd into the folder that is created after pulling

**Comment by wyzjack** [comment]
OK  I know thank you

**Comment by wyzjack** [comment]
I tried just now actually and I find should use the command' pip install -e batchgenerators' without going to the folder 'batchgenerators'

**Comment by elpequeno** [comment]
Yes, you can do that. You can also go to the folder 'batchgenerators' and use 'pip install -e .'
