### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wgs123** [MIC-DKFZ/batchgenerators#21]
raise ValueError("MirrorTransform now takes the axes as the spatial dimensions. What previously was "
ValueError: MirrorTransform now takes the axes as the spatial dimensions. What previously was axes=(2, 3, 4) to mirror along all spatial dimensions of a 5d tensor (b, c, x, y, z) is now axes=(0, 1, 2). Please adapt your scripts accordingly.

**Comment by FabianIsensee** [comment]
Hi,
all you need to know is in the error message. What part is it you need more details about?
Best,
Fabian
