### ISSUE TITLE
Missing Requirement: sklearn

### ISSUE THREAD

**Issue by justusschock** [MIC-DKFZ/batchgenerators#24]
Hi DKFZ Team, 

Due to the examples and the utilities, you got a new requirement which isn't reflected by the `requirements.txt` file: `sklearn` is used for data splitting.

Since you probably don't want the whole package to have this requirement (since this is only needed for examples), I propose the following changes:

Move `examples` to the most outer scope and move `utilities` inside `examples`. This way, you could specify another requirements file for the examples.

And while working on this, I'd also recommend moving the `tests` to the outer scope and using the `find_packages` from `setuptools` inside the setup, since this makes your whole setup process a bit more flexible.

These are just minor modifications, but especially the missing requirement could prevent future releases from being correctly installed.

Best,
Justus

EDIT: In fact, this actually prevents batchgenerators from being installed correctly. If you agree with the proposed changes, I'd open a PR for this

**Comment by justusschock** [comment]
Hi Fabian,

Mit worries, and I agree this is no critical issue (and sorry for spamming you with issues all the time).

Looks good. (You have some dependency issues in your python 2.7 test and the download URL in your setup.py seems to be outdated though)

Best,
Justus

**Comment by FabianIsensee** [comment]
Jup we are currently evaluating internally whether python 2 should still be supported or not. Currently we are leaning against it (python 2 support will end in 3 months anyways).
The new change that gets rid of the OMP_NUM_THREADS issue introduces a new dependency that does not exist for python 2.
Do you guys need python 2 support?
Best,
Fabian

**Comment by justusschock** [comment]
No, we don't, we have been using python 3.5+ only from the beginning. Just saw that in your readme and thought I should point you towards that :)

**Comment by FabianIsensee** [comment]
Thanks. Since nobody seems to object we will drop python 2 by the end of the day (already now it's failing, I was just wondering whether I should fix it :-) )
