### ISSUE TITLE
Missing Package: batchgenerators.utilities in setup.py

### ISSUE THREAD

**Issue by l-spiecker** [MIC-DKFZ/batchgenerators#26]
Hi,
"batchgenerators.utilities" is missing in setup.py. 

After installing 0.19.1 with pip or with setuptools i run into the following problem:
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
**`>>> import batchgenerators`**
_Traceback (most recent call last):_
  _File "<stdin>", line 1, in <module>_
  _File "...\batchgenerators\__init__.py", line 7, in <module>_
    _import batchgenerators.utilities_
_ModuleNotFoundError: No module named \'batchgenerators.utilities\'_

Have a nice day!

**Comment by FabianIsensee** [comment]
Hi,
thank you for pointing this out. You should be able to run `pip install --upgrade batchgenerators` to resolve this.
Best,
Fabian
