### ISSUE TITLE
Using batchgenerators with TractSeg

### ISSUE THREAD

**Issue by ilyanelken** [MIC-DKFZ/batchgenerators#27]
Hi,

I am trying to run TractSeg training, and not sure about batchgenerators version I should use.
I have tried the master and got 'PadToMultipleTransform' missing. I have also tried 'tractseg_stable' branch and there I get 'FlipVectorAxisTransform' that is missing.

I will appreciate your help.

Thanks,
Ilya

**Comment by FabianIsensee** [comment]
Hi,
I renamed them a while back because the names were pretty bad. You couldn't understand what they were really doing. @wasserth should update Tractseg to use the new (more intuitive) names :-)
Best,
Fabian

**Comment by ilyanelken** [comment]
I see. Thanks!
Ilya

**Comment by wasserth** [comment]
@ilyanelken The current `master` of TractSeg should work properly with current `master` of batchgenerators.

**Comment by ilyanelken** [comment]
@wasserth Great! Thanks a lot for help and update! Ilya

**Comment by wasserth** [comment]
@ilyanelken I just tried running TractSeg with the newest version of batchgenerators. There was a small problem but it is fixed now. So using the latest master branch should work now. Another side note: The documentation for training your own model is not completely up to date anymore. I will try to update it today or tomorrow.

**Comment by wasserth** [comment]
@ilyanelken There still seem to be some problems with the latest batchgenerators master. So I would recommend using the following commit: 802e9cbd556b9ebc1300beded7c10a37ef09b7b9
This should work best.

**Comment by ilyanelken** [comment]
@wasserth Ok! Thanks Jacob!
