### ISSUE TITLE
How to use batchgenerators for regression

### ISSUE THREAD

**Issue by adler-j** [MIC-DKFZ/batchgenerators#29]
I'm working in inverse problems and quite commonly I have a set of inputs (e.g. noisy volumes) and some outputs (noiseless volume). batchgenerators looks like a perfect fit for data augmentation, but it seems to be designed for image -> segmentation. Is there any way to work with image -> image problems, in that case how do I call the library?

**Comment by FabianIsensee** [comment]
Hi,
you just stack the desired output as an additional color channel in 'data'.
Then you make smart  use of AppendChannelsTransform. Something like this:

- 'data' is your image information stacked in c with your target output]
- do all spatial transformations, no color transformation!
- use AppendChannelsTransform to move the channel with your target into the key 'seg'. 'seg' will be created automatically (if will give a warning which you can ignore)
- now do color augmentations if applicable (brightness, contrast etc)

voila. That should do it =)

Best,
Fabian

**Comment by adler-j** [comment]
Thank you very much, this makes perfect sense!
