### ISSUE TITLE
Can I install Batchgenerators in Anaconda Environment

### ISSUE THREAD

**Issue by poornasandur** [MIC-DKFZ/batchgenerators#3]
Hi
                Can I install batchgenerators in Anaconda Environment

**Comment by FabianIsensee** [comment]
Hi,
I am not familiar with anaconda environments, but as far as I know you can just pip install it from within the environment and it should work.
Regards,
Fabian

**Comment by poornasandur** [comment]
Thank you Sir... I will try it...
