### ISSUE TITLE
Single line installation in readme

### ISSUE THREAD

**Issue by adler-j** [MIC-DKFZ/batchgenerators#30]
The current installation guide is 3-line and assumes that the user has git installed. This might be rather minor but any package on GitHub can be installed in one line without git:

```
pip install https://github.com/MIC-DKFZ/batchgenerators/archive/master.zip
```

This might be preferable for the readme.

**Comment by FabianIsensee** [comment]
Hi,
thanks for pointing this out. batchgenerators is on pypi to you can just `pip install batchgenerators`.
Best,
Fabian

**Comment by adler-j** [comment]
Great, thanks!
