### ISSUE TITLE
How to cite batchgenerators

### ISSUE THREAD

**Issue by ORippler** [MIC-DKFZ/batchgenerators#4]
Hi DKFZ,

i wish to cite the batchgenerators repository in a publication, as it's a  pretty awesome framework.
Any preferred way on how to do so?

Best,

**Comment by FabianIsensee** [comment]
Hi,
I am glad to hear you appreciate our framework =)
As of now we don't have a software publication or DOI. We might want to change that.
For now (if you want) you could just write that you used it along with a link to our repository.
Best,
Fabian
