### ISSUE TITLE
example_ipynb: cannot import name 'Mirror'

### ISSUE THREAD

**Issue by qwe120236456** [MIC-DKFZ/batchgenerators#40]
Dear Fabian,
I tried to run the example but got an error :
ImportError: cannot import name 'Mirror'
I checked spatial_transforms.py but only found `MirrorTransform`.
I am confused and cannot fix it, hope you could help me.
Best,
Ce Liang

**Comment by FabianIsensee** [comment]
You are right. This is supposed to be MirrorTransform. It was called Mirror a long time ago :-)
I will try to find the time and change that today, but until then you can just edit that manually
Best,
Fabian
