### ISSUE TITLE
test  normalization

### ISSUE THREAD

**Issue by xihuanliuliu** [MIC-DKFZ/batchgenerators#41]
Dear FabianIsensee:
I use the example of a brats2017_preprocessing. I found that the train sample use normalization preprocessing with the label, but the test data only have image, What should I do ?

**Comment by FabianIsensee** [comment]
This setup is meant to run training only. It is not meant for testing. Due to the patch based nature AND the different sizes of the images, running this for testing is not possible
Best,
Fabian
