### ISSUE TITLE
use batchgenerators as ImageDataGenerator in keras

### ISSUE THREAD

**Issue by moreabs** [MIC-DKFZ/batchgenerators#43]
dear Fabian Isensee:
hi. i am new in python and keras. i use your batchgenerator and i gave data loader entire dataset and add some transformation  but how can i use your batchgenerator as ImageDataGenerator in keras to train my model? do i have to write Custom Keras Generators  with your generator or not?
thank you in advance

**Comment by FabianIsensee** [comment]
Hi,
I don't have any keras experience so I am afraid I cannot help you :-/
Best,
Fabian
