### ISSUE TITLE
A question about spatial_transforms

### ISSUE THREAD

**Issue by EricKani** [MIC-DKFZ/batchgenerators#45]
Hi,

Thanks for your sharing of your augmentation code. I have a question about ''augment_channel_translation'' in ''spatial_transforms.py''. 

What is the meaning of this augment method? Does it in order to prevent the impact of poor registration between different modality of one object？（different modality: like RGB and Depth in netural image; CT and MRI and PET in medical image. One modality is one channel)

Thanks.

Best,

Eric Kani

**Comment by FabianIsensee** [comment]
Hi Eric,
exactly. It will misalign the 'color' channels (translation only) to simulate bad registration. I have not used it though, so I cannot say how well this works as an augmentation.
Best,
Fabian
