### ISSUE TITLE
Need some advice

### ISSUE THREAD

**Issue by PaladinYM** [MIC-DKFZ/batchgenerators#47]
Hi,
Thanks for sharing your augmentation code. I'm studying on medical image preprocessing and want to get some advice.
In your paper **An attempt at beating the 3D U-Net**, you mentioned that you made use of scaling, rotations, brightness, contrast, gamma and Gaussian noise augmentations. Would you mind share some details about your strategy, like using theses augmentations separately or combine them in a specific order?
I would appreciate it very much if you are willing to give me some help!
Best,
Chen

**Comment by PaladinYM** [comment]
Find it in [nnUNet](https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunet/training/data_augmentation) :). Sorry to disturb.

**Comment by FabianIsensee** [comment]
Glad you found it!
The strategy in the paper you mentioned is a little different but the nnunet configuration should be a good starting point.
Best,
Fabian
