### ISSUE TITLE
A question about compatibility about transforms

### ISSUE THREAD

**Issue by Willzy-x** [MIC-DKFZ/batchgenerators#48]
Hi, 

The tranforms are very comprehensive and useful, but I was wondering whether those transforms are compatible with `torchvision.transforms.Compose().`
I noticed that batchgenerators also provided  `Compose()` function and `Dataloader`. However, my work was mostly composed with pytorch and its related tools. And I hope to use the transforms of batchgenerators in pytorch's `Dataloader`, which helps minimize my workload.

Best ,
Yucheng

**Comment by FabianIsensee** [comment]
Hi,
I have never used the pytorch data loader so I don't know. Sorry :-/
Best,
Fabian

**Comment by Willzy-x** [comment]
Hi,
That was disappointing... I have to refactor my codes now to adjust to the transforms in `batchgenerators`. By the way, do you have the intention to make it more compatible with popular frameworks? Just curious.
Best,
Yucheng

**Comment by FabianIsensee** [comment]
Well batchgenerators was created before pytorch existed, so that's why it looks different. We could change it to make it more compatible, but right now nobody on our team has the time to do this, as this would also require us to refactor a lot of internal code

**Comment by Willzy-x** [comment]
Well, that's fine. I think `batchgenerators` is a really useful tool for medical imaging processing, and I believe making it more compatible with popular frameworks will help more people. 👍

**Comment by jchen42703** [comment]
Note that it works with torch (just use numpy arrays and convert to tensors at the end) but def not compatible with torchvision
