### ISSUE TITLE
Need help about the MultiThreadedAugmenter

### ISSUE THREAD

**Issue by Willzy-x** [MIC-DKFZ/batchgenerators#50]
Hi,
I am trying to emulate the `brats2017DataLoader3D` to get my `Kits2019DataLoader3D`, but I encounter the following problem. My program stopped at `batch = next(tr_gen)` when I used the `MultiThreadedAugmenter`(I tried the `SingleThreadedAugmenter` as well, which works fine on my laptop). I also try to debug it, but nothing just happened. When I look out the processes that created on my computer by using htop, I found a lot of complexing processes created by the program even if I have terminated it. Therefore, I was wondering whether there are some problems with my code or the `MultiThreadedAugmenter`.

<img width="1802" alt="Screen Shot 2019-11-06 at 10 10 00 AM" src="https://user-images.githubusercontent.com/34648086/68262654-e4a32d80-007e-11ea-983b-81d9fbe77634.png">

`if __name__ == "__main__":
    preprocessed_folders = "./npy_data"
    num_of_threads_for_kits19 = 4

    patients = get_list_of_patients(preprocessed_data_folder=preprocessed_folders)

    train, val = get_split_deterministic(patients, fold=0, num_splits=2, random_state=12345)

    patch_size = (128, 160, 160)
    batch_size = 4

    # dataloader = Kits2019DataLoader3D(train, batch_size, patch_size, 1)

    # batch = next(dataloader)
    # try:
    #     from batchviewer import view_batch
    #     # batch viewer can show up to 4d tensors. We can show only one sample, but that should be sufficient here
    #     view_batch(batch['data'][0], batch['seg'][0])
    # except ImportError:
    #     view_batch = None
    #     print("you can visualize batches with batchviewer. It's a nice and handy tool. You can get it here: "
    #           "https://github.com/FabianIsensee/BatchViewer")

    # now we have some DataLoader. Let's go and get some augmentations

    # first let's collect all shapes, you will see why later
    shapes = [Kits2019DataLoader3D.load_patient(
        i)[0].shape[1:] for i in patients]
    max_shape = np.max(shapes, 0)
    max_shape = np.max((max_shape, patch_size), 0)

    # we create a new instance of DataLoader. This one will return batches of shape max_shape. Cropping/padding is
    # now done by SpatialTransform. If we do it this way we avoid border artifacts (the entire brain of all cases will
    # be in the batch and SpatialTransform will use zeros which is exactly what we have outside the brain)
    # this is viable here but not viable if you work with different data. If you work for example with CT scans that
    # can be up to 500x500x500 voxels large then you should do this differently. There, instead of using max_shape you
    # should estimate what shape you need to extract so that subsequent SpatialTransform does not introduce border
    # artifacts
    dataloader_train = Kits2019DataLoader3D(
        train, batch_size, patch_size, num_of_threads_for_kits19)

    # during training I like to run a validation from time to time to see where I am standing. This is not a correct
    # validation because just like training this is patch-based but it's good enough. We don't do augmentation for the
    # validation, so patch_size is used as shape target here
    dataloader_validation = Kits2019DataLoader3D(
        val, batch_size, patch_size, num_of_threads_for_kits19)

    tr_transforms = get_train_transform(patch_size)

    # tr_gen = SingleThreadedAugmenter(dataloader_train, transform=tr_transforms)
    # val_gen = SingleThreadedAugmenter(dataloader_validation, transform=None)
    # finally we can create multithreaded transforms that we can actually use for training
    # we don't pin memory here because this is pytorch specific.
    tr_gen = MultiThreadedAugmenter(dataloader_train, tr_transforms, num_processes=num_of_threads_for_kits19,
                                    num_cached_per_queue=3,
                                    seeds=None, pin_memory=False)
    # we need less processes for vlaidation because we dont apply transformations
    val_gen = MultiThreadedAugmenter(dataloader_validation, None,
                                     num_processes=max(1, num_of_threads_for_kits19//2), num_cached_per_queue=1,
                                     seeds=None,
                                     pin_memory=False)

    # lets start the MultiThreadedAugmenter. This is not necessary but allows them to start generating training
    # batches while other things run in the main thread
    tr_gen.restart()
    val_gen.restart()

    # now if this was a network training you would run epochs like this (remember tr_gen and val_gen generate
    # inifinite examples! Don't do "for batch in tr_gen:"!!!):
    '''
    num_batches_per_epoch = 10
    num_validation_batches_per_epoch = 3
    num_epochs = 5
    # let's run this to get a time on how long it takes
    time_per_epoch = []
    start = time()
    for epoch in range(num_epochs):
        start_epoch = time()
        for b in range(num_batches_per_epoch):
            batch = next(tr_gen)
            # do network training here with this batch

        for b in range(num_validation_batches_per_epoch):
            batch = next(val_gen)
            # run validation here
        end_epoch = time()
        time_per_epoch.append(end_epoch - start_epoch)
    end = time()
    total_time = end - start
    print("Running %d epochs took a total of %.2f seconds with time per epoch being %s" %
          (num_epochs, total_time, str(time_per_epoch)))
          '''

    # if you notice that you have CPU usage issues, reduce the probability with which the spatial transformations are
    # applied in get_train_transform (down to 0.1 for example). SpatialTransform is the most expensive transform
    from batchviewer import view_batch
    # if you wish to visualize some augmented examples, install batchviewer and uncomment this
    if view_batch is not None:
        for _ in range(4):
            batch = next(tr_gen)
            view_batch(batch['data'][0], batch['seg'][0])
    else:
        print("Cannot visualize batches, install batchviewer first. It's a nice and handy tool. You can get it here: "
              "https://github.com/FabianIsensee/BatchViewer")`

Best,
Yucheng

**Comment by FabianIsensee** [comment]
Hi,
it looks like you were going out of memory?
I would recommend to use the preprocessing in the nnU-net repository and also using the DataLoader3d from there.
https://github.com/MIC-DKFZ/nnUNet
Best,
Fabian

**Comment by FabianIsensee** [comment]
Please also make sure to use the very newest version of batchgenerators (pull form github and install that code, not pip install)

**Comment by Willzy-x** [comment]
My batchgenerators' version is 0.19.5. Is that a problem?

**Comment by FDSJK** [comment]
Hi, when I used the MultiThreadedAugmenter, I got the error as follow:
Traceback (most recent call last):
  File "D:/JIHONG/Documents/python_files/New_pro/Multi_process.py", line 82, in <module>
    data = next(tr_gen)
  File "C:\Program_Files\Anaconda3\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 193, in __next__
    self._start()
  File "C:\Program_Files\Anaconda3\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 229, in _start
    self._processes[-1].start()
  File "C:\Program_Files\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program_Files\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program_Files\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program_Files\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program_Files\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle SwigPyObject objects

Process finished with exit code 1
If it is necessary, I can share my source code
I really need help for the cause of the error

**Comment by FabianIsensee** [comment]
Hi,
this is not related to batchgenerators but to python multiprocessing. You seem to have a SwigPyObject somewhere in the pipeline and that cannot be pickled (it needs to be picklable so that multiprocessing can work). Try finding that object (probably in your dataset class?) and replacing that with something that can be pickled.
Best,
Fabian

**Comment by hfzarslan** [comment]
I am getting this error can anyone help me 
ImportError: cannot import name 'MultiThreadedAugmenter' from 'batchgenerators.dataloading'
