### ISSUE TITLE
tests folder is installed to wrong place

### ISSUE THREAD

**Issue by hubutui** [MIC-DKFZ/batchgenerators#52]
It seems that `tests` folder is installed to `site-packages/tests`, it should be install to `site-packages/batchgenerators/tests` or we just don't installed it at all.

**Comment by FabianIsensee** [comment]
Hi,
you are absolutely right, sorry for the inconvenience! I have now removed tests from the packages that are installed. I will do a new release later today.
Best,
Fabian
