### ISSUE TITLE
How to implement customized enhancment function?

### ISSUE THREAD

**Issue by awp4211** [MIC-DKFZ/batchgenerators#53]
In some situation, we need to implement our own enhancement algorithm, such as top hat contrast enhancement algorithm. How to implement it and embed into class MultiThreadedAugmenter?

**Comment by FabianIsensee** [comment]
Hi,
please have a look at any of the transforms that already exist. Multithreadedaugmenter is not the right place to implement custom augmentations.
Best,
Fabain

**Comment by FabianIsensee** [comment]
For example 
https://github.com/MIC-DKFZ/batchgenerators/blob/400390d37b7a3898de08fdd925ede18627ae50c8/batchgenerators/transforms/color_transforms.py#L21
