### ISSUE TITLE
Wrong names formatting on Zenodo

### ISSUE THREAD

**Issue by fepegar** [MIC-DKFZ/batchgenerators#55]
Hi,

I'm trying to cite you using the entry on Zenodo. The names are `Isensee Fabian; Jäger Paul`, etc. That way, the BibTeX format is not generated correctly. You should change it to `Isensee, Fabian; Jäger, Paul`, etc.

By the way, you can automate the releases and this stuff using a Zenodo config file, as NiBabel guys do.

**Comment by FabianIsensee** [comment]
Thanks for pointing this out! @wasserth could you please take care of that?

**Comment by wasserth** [comment]
Thanks for pointing this out. I added the comma to the names on the Zenodo page.
We thought about doing automatic releases to Zenodo, but decided that for now this is not needed. We might add it in the future.
