### ISSUE TITLE
Multiplication between coordinates and transform matrix takes all processors

### ISSUE THREAD

**Issue by TheoEst** [MIC-DKFZ/batchgenerators#57]
Hello Fabian, 

Thanks for sharing all this code for the community. 

I used your code to implement a affine transformation data augmentation functions using Pytorch and 3D Images.  I used the same idea with coords, transform matrix and scipy map_coordinates functions. 

I have a trouble when I multiply the coords by the transform matrix (with numpy np.matmul or np.dot). The numpy functions takes the processors available and block all other experiments running on our cluster.
 
We are sharing a server with 8 GTX 1080 and 48 processors with 5 people using it, so if one people takes all process, it create trouble for other users 
Did you notice the same behavior and find a way to prevent it ? 
It seems that it is the default behavior of numpy to parallelise on all the available CPUs.
(I put the workers=0 option in the pytorch dataloader). 

Also to be sure, I tested np.dot( np.random.randn(4, 4), np.random.randn(4, 64*64*64) ) and it gives the same behaviour of using all the process. 

Thanks for the help,
Best regards,

**Comment by FabianIsensee** [comment]
Hi there,
yes we had the same issue. This is caused by numpy. Downgrading numpy will solve this, but depending on what you are doing this is not a good solution.
A better solution is to set OMP_NUM_THREADS=1 on the bashrc. But this is still not perfect because this also affects other processes and every user has to do this themselves.
The best solution in my opinion is what we are currently doing in batchgenerators: threadpoolctl. 
https://github.com/joblib/threadpoolctl

It's a fantastic package :-)
Best,
Fabian

**Comment by TheoEst** [comment]
Hi,

Thanks a lot for your quick answer and the advice. I will try to explore the threadpoolctl. 
Do you think it is Pytorch compatible ? 

One of my idea was to split my coords array in smaller array and doing the multiplication sequentially. But I am not sure it will prevent numpy from parallelize. 



Two modifications I made from your Affine Transform pipeline (maybe you made it and I didn't pay attention or you have good reasons not to do it). 

- When I combine rotation, scale, shear etc... I store the 4*4 transformation matrix and I multiply the transformation matrix by the rotation, then scale in order to keep to 4*4 multiplication. And only at the end, I multiply to the coords. Actually I took that from keras pipeline. I have the impression that you multiply the coords every time.

- If I do crop my input mri, I crop the coords matrix by slicing before apply the map_coordinates, in order to reduce the size of the interpolation and gain calculation time.

Best regards, 
Théo

**Comment by FabianIsensee** [comment]
Hi,
thanks for the advice! I think your way of doing the scaling is superior to what we are currently doing. I will have a look at it as soon as I can.
From my understanding, the computation time of map_coordinates scales with the size of the coordinate grid, not the size of the array that grid is in. So cropping the array is not necessary. But again, this is something one would have to time to really see the difference.

As you can see here 

https://github.com/MIC-DKFZ/batchgenerators/blob/967e4c9630491ccc029f1a0eba93d2028547a42a/batchgenerators/dataloading/multi_threaded_augmenter.py#L231

We set the threadpool limit context only for spawning the background workers. After that the threadpool is reset to what it usually is. This will make sure only the background workers are affected and pytorch can do as it pleases :-)

Best,
Fabian

**Comment by TheoEst** [comment]
Ok, I just tested it, it is working perfectly. 
Thanks a lot

And for the cropping, yes I am cropping the coordinates grid, having a cropped_coords grid and then apply the map_coordinates.

**Comment by FabianIsensee** [comment]
Why are you cropping the corrdinate grid? In our implementation the grid is created in the correct size to begin with, so it does not have to be cropped

**Comment by TheoEst** [comment]
Ah, that's probably this point that I didn't notice. 
I am creating the grid with     

z, y, x = (np.arange(i) for i in shape)
coords = np.array(np.meshgrid(z, y, x, indexing='ij')).astype(float)

shape being the originale shape of my mri.  And then I apply 

coords = coords[:, depth_min:depth_max,
                               height_min:height_max,
                               width_min:width_max]
Depending on the crop functions I am using (random and so...)
But you are right, I could create the coords directly to the good shape, it will avoid storing a bigger matrix for nothing. Probably will not change a lot of computation time

**Comment by FabianIsensee** [comment]
As long as you do the multiplication after cropping it should not make a big difference, except for the unnecessarily large array that is created at the start
