### ISSUE TITLE
maybe_mkdir_p does not work on Windows

### ISSUE THREAD

**Issue by nlessmann** [MIC-DKFZ/batchgenerators#69]
I read that Windows-support is only experimental, but one of the functions that does really not work is `maybe_mkdir_p()` since it splits the path based on a hardcoded forward slash.

A quick fix could be to switch to the mkdir function of the Path class from pathlib:

```python
from pathlib import Path

def maybe_mkdir_p(directory):
    Path(directory).mkdir(parents=True, exist_ok=True)
```

**Comment by FabianIsensee** [comment]
Sounds like a good solution to me. If you want you can make a pull request so that people can see this part comes from you. If not I can quickly change that myself. As you like.
Best,
Fabian

**Comment by FabianIsensee** [comment]
Thanks :-)
