### ISSUE TITLE
When inference phase, how can we ensure that we have adequate brain sampling (i.e. The obtained patches can fully cover the whole brain area)

### ISSUE THREAD

**Issue by 675492062** [MIC-DKFZ/batchgenerators#71]
When inference phase, how can we ensure that we have adequate brain sampling (i.e. The obtained patches can fully cover the whole brain area)? 
1)BraTS2017DataLoader3D and crop method may not have this function. Is  there any demo for users?
2)In BraTS2017DataLoader3D, "get_split_deterministic" can get a random training && validation set split, but only the one fold of them, which is no use usually. Mostly, we gain the whole training && validation pairs split, and do validation after training on the corresponding training split. Finally ,we should finish training on all split.

**Comment by FabianIsensee** [comment]
Hi,
batchgenerators is only intended for training. At test time you need to implement that yourself. Each method will have its own requirements so it will be hard to provide something that works for all applications. If you want to have some inspiration you could have a look at the nnU-Net inference code: https://github.com/MIC-DKFZ/nnUNet/blob/b4f69956ba4c50d44316650b77a75751c426a647/nnunet/network_architecture/neural_network.py#L287

Best,
Fabian

**Comment by 675492062** [comment]
Thanks for your reply!  I see!
