### ISSUE TITLE
[Question] apply the same SpatialTransform to two batches

### ISSUE THREAD

**Issue by BUAAxiaobaige** [MIC-DKFZ/batchgenerators#75]
Hi, thank you very much for sharing such a wonderful repository！
I am using the SaptialTransform and applying it to both the original images and their labels, but it makes me puzzled that each time I use SaptialTransform, it will randomly generate the result. For example, when the original picture is processed in one way, but its label will be processed in another way (I want to process the original picture and its label in the same way).  I tried to find whether there is a way to control the random seeds but didn't find one. How can I deal with this problem?
Thank you very much for your help. 
(my English is poor, and hope it will not cause much trouble for your reading)

**Comment by FabianIsensee** [comment]
are you working on a segmentation problem? You should save your segmentation in the 'seg' key of the dictionary. Then it will be augmented the same as the data

**Comment by BUAAxiaobaige** [comment]
> are you working on a segmentation problem? You should save your segmentation in the 'seg' key of the dictionary. Then it will be augmented the same as the data

thank you, it really works!

**Comment by FabianIsensee** [comment]
glad to hear that!
