### ISSUE TITLE
Questions about adding Normalization as data augmentation

### ISSUE THREAD

**Issue by QiushiYang** [MIC-DKFZ/batchgenerators#76]
According to the function: get_train_transform of brats2017_dataloader_3D.py, it seems that there is no Normalization for the inputs after all the other augmentation operations. Wonder why and whether it will be useful to add the normalizaiton as the final step of augmentation?
Also, another question is that is it reasonable to add GaussianNoiseTransform as a kind of augmentation? (Considering that in the testing data, it seems that there is no much Gaussian noises actually.)

**Comment by FabianIsensee** [comment]
Do not use batchgenerators for inference. Batchgenerators is for training only.
The normalization is part of the preprocessing. This computation is done beforehand. It makes no sense to repeat this over and over again on the fly and waste computation time ;-)

**Comment by QiushiYang** [comment]
Thank you so much for your so quick helps. I have another question that will it be more useful to do data augmentation offline beforehand to get a stable training process than doing it on the fly?

**Comment by FabianIsensee** [comment]
Always on the fly! This allows you to get an infinite number of augmented samples. Never run data augmentation offline!
This has no effect on stability

**Comment by QiushiYang** [comment]
Thanks a lot! I will have a try again.
