### ISSUE TITLE
Error Importing SlimDataLoaderBase

### ISSUE THREAD

**Issue by sbadih** [MIC-DKFZ/batchgenerators#93]
Hi, 
I'm trying to run the training portion, however I keep getting this error " ImportError: cannot import name 'SlimDataLoaderBase' from 'batchgenerators.dataloading' (/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/__init__.py)". Any ideas on how to fix this?

Best,
Sara Badih

**Comment by FabianIsensee** [comment]
Since the lastest version we have changed the imports so something that is more sustainable. You will need to change your imports (depending on your IDE you can use autocomplete for that).
Best,
Fabian

**Comment by sbadih** [comment]
Can you please elaborate on the ways it can be imported? I'm using Jupyter Notebook specifically, and I've followed the required versions for Python etc on the documentation. Thank you.

**Comment by FabianIsensee** [comment]
`from batchgenerators.dataloading.data_loader import SlimDataLoaderBase`

you guys really need to stop using jupyter notebook for coding ^^
