### ISSUE TITLE
ImportError: cannot import name 'MultiThreadedAugmenter' from 'batchgenerators.dataloading'

### ISSUE THREAD

**Issue by Ankush-Kesri** [MIC-DKFZ/batchgenerators#99]
Hi,

Whenever I am trying to run nnUNet fot training, I am getting the following error.

ImportError: cannot import name 'MultiThreadedAugmenter' from 'batchgenerators.dataloading'   (.......lib/python3.10/site-packages/batchgenerators/dataloading/__init__.py)

I would appreciate you help is resolving this issue/error,

Thank you.

**Comment by ZoeyJiang** [comment]
Hi,
I also met this error, May I ask whether you solve it and how do you solve it?
I am looking forward to your reply.
Thanks

**Comment by Ankush-Kesri** [comment]
Hi @ZoeyJiang,

My senior at work figured out the solution. 
These functions can't be imported because they don't exist in the mentioned directory that is 'batchgenerators.dataloading', These functions are inside their separate modules inside this path.

So try replacing
( from batchgenerators.dataloading import MultiThreadedAugmenter, SingleThreadedAugmenter )
to 
( from batchgenerators.dataloading.multi_threaded_augmenter import MultiThreadedAugmenter
from batchgenerators.dataloading.single_threaded_augmenter import SingleThreadedAugmenter )
in the module at location mentioned just above the error you are getting.

I hope it helps.

**Comment by ZoeyJiang** [comment]
Thanks for your sharing. I will try your suggestions
